export default {
    countCells: 7,
    massive: [
        {
            dataField: 'okv0',
            cols: 1,
            rows: 2,
            text: 'Виды экономической деятельности (по разделам ОКВЭД)',
            class: 'd-flex flex-row align-center justify-start ',
            headerClass: 'align-end ',
            headerStyles: `min-width: 350px;`,
            order: 0,
            variable: false,
            // template: (row) => {
            //     return row.sprKcpGroupId + ' - ' + row.sprKcpGroupName
            // }
        },
        {
            dataField: 'npg11',
            cols: 3,
            rows: 1,
            text: 'по программам повышения квалификации в 2020 г.',
            order: 1,
            variable: false,
        },
        {
            dataField: 'npg111',
            cols: 3,
            rows: 1,
            text: 'по программам профессиональной переподготовки в 2020 г.',
            order: 1,
            variable: false,
        },

        {
            dataField: 'npg31',
            cols: 1,
            rows: 1,
            text: `все формы`,
            order: 5,
            variable: false,
        },
        {
            dataField: 'npg32',
            cols: 1,
            rows: 1,
            text: `очно-заочно`,
            order: 5,
            variable: false,
        },
        {
            dataField: 'npg33',
            cols: 1,
            rows: 1,
            text: `заочно`,
            order: 5,
            variable: false,
        },
        {
            dataField: 'npg34',
            cols: 1,
            rows: 1,
            text: `все формы`,
            order: 5,
            variable: false,
        },
        {
            dataField: 'npg35',
            cols: 1,
            rows: 1,
            text: `очно-заочно`,
            order: 5,
            variable: false,
        },
        {
            dataField: 'npg36',
            cols: 1,
            rows: 1,
            text: `заочно`,
            order: 5,
            variable: false,
        },
        {
            dataField: 'okv',
            cols: 1,
            rows: 1,
            headerClass: 'd-flex flex-row justify-start',
            class: 'justify-start d-flex flex-row text-left',
            text: `1`,
            order: 6,
            variable: true,
        },
        {
            dataField: 'nvpks21Pk1',
            cols: 1,
            rows: 1,
            text: `3`,
            order: 7,
            variable: true,
        },
        {
            dataField: 'nvpkv21Pk1',
            cols: 1,
            rows: 1,
            text: `4`,
            order: 8,
            variable: true,
        },
        {
            dataField: 'nvpkz21Pk1',
            cols: 1,
            rows: 1,
            text: `5`,
            order: 9,
            variable: true,
        },
        {
            dataField: 'nvpps21Pk1',
            cols: 1,
            rows: 1,
            text: `6`,
            order: 7,
            variable: true,
        },
        {
            dataField: 'nvppv21Pk1',
            cols: 1,
            rows: 1,
            text: `7`,
            order: 8,
            variable: true,
        },
        {
            dataField: 'nvppz21Pk1',
            cols: 1,
            rows: 1,
            text: `8`,
            order: 9,
            variable: true,
        },
    ]
}
